# Simple deployment used to deploy and manage the app in nigelpoulton/ps-web:1.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-deploy
  labels:
    app: scraper
spec:
  selector:
    matchLabels:
      app: scraper
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: scraper
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: scraper-pod
        image: javierorta/cdmx-scraper:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80