# Simple deployment used to deploy and manage the app in nigelpoulton/ps-web:1.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-deploy
  labels:
    app: rest
spec:
  selector:
    matchLabels:
      app: rest
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: rest
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: rest-pod
        image: javierorta/cdmx-rest-api:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9443
        - containerPort: 9000