apiVersion: v1
kind: Service
metadata:
  name: rest-nodeport
spec:
  type: NodePort
  ports:
  - name: https
    port: 9443
    targetPort: 9443
    protocol: TCP
  - name: http
    port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: rest
    